import inc.db as db
import random,string
import inc.email_handler as EH


# host='http://onnetwork.ddns.net'
host='http://192.168.3.40:8000'


def register(username,email,password):
    # inserting user data in the database.
    q='''
        INSERT INTO users (username, password, email, verified)
        VALUES ( '{username}', '{password}',  '{email}', false);
    '''.format(username=username,password=password,email=email)
    res=db.sendQuery(q)

    # getting the user id that was generated by the database.
    q='''
    select id from users where username= '{username}'
    '''.format(username=username)
    user_id=db.sendQuery(q)[0][0]
    # generating a unique verification code for email verification.

    code=''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(64))
    q='''
        select * from verification_codes where vc = '{code}'
    '''.format(code=code)
    res=db.sendQuery(q)

    while len(res)>0:
        code=''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(64))
        q='''
        select * from verification_codes where vc = '{code}'
        '''.format(code=code)
        res=db.sendQuery(q)
    # inserting the verification code to the verification table.

    q='''
        INSERT INTO verification_codes (user_id, vc, time)
        VALUES ( '{user_id}', '{code}',now());
    '''.format(user_id=user_id,code=code)
    res=db.sendQuery(q)

    q='''
        INSERT INTO account_type (u_id, acc_type)
        VALUES ( '{user_id}', 0);
    '''.format(user_id=user_id)
    res=db.sendQuery(q)
    # sending the email using the email_handler.py
    EH.sendRVE(username,email,host,code)

